version: '3'

services:
  db:
    container_name: mongo-db-nest25
    image: mongo:6.0.6
    volumes:
      - ./dockerMongoDBData:/data/db
    ports:
      - 27017:27017
    restart: always
